Make GF256 hashable in Python 2.6.
Python 2.5 has a default fallback where id(x) was used if x had not
__hash__ method, but in Python 2.6 one gets the error

  exceptions.TypeError: unhashable type: 'GF256'

instead. Defining a suitable __hash__ method solves this.